---
apiVersion: v1
kind: Namespace
metadata:
  name: open
  labels:
    namespaceclass.akuity.io/name: public-network

---
apiVersion: v1
kind: Namespace
metadata:
  name: close
  labels:
    namespaceclass.akuity.io/name: internal-network

# Resources in the open namespace
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: open
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: open
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"

# Resources in the close namespace
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: close
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: close
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
